# Generated by Django 5.0.2 on 2025-08-09 18:48

import forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen del formulario', null=True, upload_to=forms.models.images_directory_path),
        ),
    ]
