# Generated by Django 5.0.2 on 2025-08-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_form_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción del formulario', null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen del formulario', null=True, upload_to='media/formsimg'),
        ),
    ]
