# Generated by Django 5.0.2 on 2025-08-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_form_description_alter_form_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticplan',
            name='ai_generated_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
